version: "3.9"
services:
  discord-blue-archive-bot:
    container_name: discord-blue-archive-bot
    build: .
    volumes:
      - ./Data:/app/Data
    restart: unless-stopped
    env_file:
      - .env