// <auto-generated />
using System;
using DiscordBlueArchiveBot.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBlueArchiveBot.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230817091441_UserGacheCharacterRecord")]
    partial class UserGacheCharacterRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("DiscordBlueArchiveBot.DataBase.Table.CafeInviteTicketUpdateTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotifyDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CafeInviteTicketUpdateTime");
                });

            modelBuilder.Entity("DiscordBlueArchiveBot.DataBase.Table.NotifyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotifyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NotifyConfig");
                });

            modelBuilder.Entity("DiscordBlueArchiveBot.DataBase.Table.UserGachaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PickUpCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ThreeStarCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TotalGachaCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserGachaRecord");
                });

            modelBuilder.Entity("DiscordBlueArchiveBot.DataBase.Table.UserGacheCharacterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("Num")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserGacheCharacterRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
